### ISSUE TITLE
wiki-node-server + wiki-client : allow anonymous, collaborative wikis by config + local wiki configs in a farm + multiple editors per wiki

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki#12]
Currently I'm hacking `wiki-client` to not display the login button at all, to provide loginless Wikis from time to time.

---
### 1. single site servers

This would mean the server is presented the `--anonymous`/`--no-authentication`/`-noauth` flag, intervening with `wiki-client` not to present the Login Button.
### 2 farms

In the farm case, sometimes I don't want to disable the login for all sites, else refer to **1.**.

It could be nice to add additional metadata to the initial `welcome-visitors` json, in a place that cannot be edited if anonymous, that provides additional information about a wiki, like the idea above.

I might be playing with just pasting arbitrary JSON into one of the existing factories, to see how it behaves.

If that works, a key-value pair like `noauth:true` would already be enough for the server and client not to show login at all.

---
### multiple authentication for collaborative wikis

As of now, every wiki only supports one user. In certain environments, people (i.e. @hhalpin) want to have a mix of Etherpads and Wikipedia. Hackpad does something very similiar already today, but lacks open sources (and belongs to Dropbox > Condoleezza Rice ...).

WebID (@bblfish) could help to provide this authentication layer for an also semantic wiki implementation. Also see https://github.com/WardCunningham/Smallest-Federated-Wiki/issues/411 for discussions about Semantics and Federated Wiki.

**Comment by i2p-lbt** [comment]
I got the impression that the Login is an essential principle of how wikis work, though still not sure. So operating a wiki-site completely without might be a rather special case of operational mode. And the "outsourced" credentials is really sexy in a way, because you automatically transfer those credentials with each page's history while keeping them intact on an other server. Right?

A +1 from me for being able to allow anonymous contributions, though. Like an "allow anon contributions" switch. Maybe a good way would be to just have an "anonymous" role then and assigning that automatically if a user is not logged in? Maybe with a hint to do the log-in if one is the author? Not sure about the whole change process atm, but that is a feature I expected from FedWikis and that would be nice to have for people that do not want to / are not able to use an OpenID. Not sure if this is the same issue as "forbid Login", though ...

**Comment by almereyda** [comment]
This is resolved with the friends security plugin.

- https://github.com/fedwiki/wiki-security-friends
