### ISSUE TITLE
Wiki pages with a long list of wiki links stopped paginating correctly? 

### ISSUE THREAD

**Issue by cliveb** [fedwiki/wiki#137]
Please see this page, scroll down to later entries. http://clive.tries.fed.wiki/view/welcome-visitors/view/deep-thoughts-on-wiki

Related, unsure, but I noticed this after forking this page with recent changes list appended (apparently, I somehow appended the recent changes list) http://clive.tries.fed.wiki/view/welcome-visitors/view/recent-changes/view/macbook-air-m1-2020

**Comment by paul90** [comment]
@cliveb not sure I'm seeing an issue, but if you are available to demonstrate this issue on the dojo call on Sunday it would be good.

**Comment by cliveb** [comment]
@paul90 I will plan to demo on Sunday. Just in case, I took some screen shots, to preview the main issue. 

I noticed @Frank owner of page macbook-air-m1-2020 remarked rosters are not working equally across different OS. MacOS Monterey and ChromeOS, which is generally always built from the latest Chromium.org.

![Screenshot 2021-12-02 11 05 47 PM](https://user-images.githubusercontent.com/733870/144560336-323f8233-9455-4ce1-9434-879986064a5c.png)

![Screenshot 2021-12-02 11 06 09 PM](https://user-images.githubusercontent.com/733870/144560284-99d34eb5-4681-443e-be8a-be82c602533a.png)

![Screenshot 2021-12-02 11 06 32 PM](https://user-images.githubusercontent.com/733870/144560266-ffecd023-50fa-4929-920d-24d285e887ee.png)

**Comment by cliveb** [comment]
Update. I tested long list pagination on the latest production releases of Chrome, Firefox and Safari. They all paginate a long list or wiki pages incorrectly (as screenshots above).

**Comment by paul90** [comment]
By incorrectly, do you mean that the last item in a screen full is at the top of the next one when you scroll down? That is normal browser behaviour.

**Comment by WardCunningham** [comment]
In discussion today, we came to understand that the problem was irregular spacing due to a history of trying various plugin types for an item consisting of a single link. These all worked as links but spacing items differently.

I volunteered to write a Frame script that would force each item to be of type paragraph. I also suggested adding page folds every month. I wasn't sure this was desired. I can remove this modification upon request. I've condensed the journal into a single create action which discards previous history but will make new changes record properly.

![image](https://user-images.githubusercontent.com/12127/145314410-74f38fd1-9161-48c0-88b0-a372c6b030f7.png)

The script appears on this page:
http://ward.dojo.fed.wiki/rewrite-page.html

![image](https://user-images.githubusercontent.com/12127/145314004-6bc8bb6b-e694-4c72-ab59-96b0dfc2d330.png)

Clive can test this code by opening this page, dragging the page to his site, the pressing 'preview' to see the proposed modifications. If this is judged an improvement the "ghost" preview can be forked into Clive's site.

**Comment by cliveb** [comment]
I pressed preview. The result is terrific. I forked the page to my site. Great work. 

btw, I continue to learn and think quite a lot about about wiki, json and plugins, as plugin-objects with--nothing more, just sufficient--plugin-capabilities. 

http://clive.tries.fed.wiki/view/welcome-visitors/view/deep-thoughts-on-wiki
