### ISSUE TITLE
How to convert a federated wiki into a farm (or subdomains)?

### ISSUE THREAD

**Issue by coevolving** [fedwiki/wiki#49]
Last year, I started a Wiki Openshift Quickstart based on the instructions from @paul90 to create a wiki.   This led to instructions at http://fed.coevolving.com/view/wiki-openshift-quickstart .

In using the wiki, and starting to federate content from other sites, I noticed that searches were starting to return a ridiculous number of irrelevant hits, as the search wouldn't be only on my domain, but other domains as well.

In the fall, I learned from @WardCunningham that the way to keep neighbourhoods small is to run multiple wikis.  This makes sense, as when I'm working within a limited interest, I don't really want to be searching the world.

The way that Ward does this seems to be by managing multiple subdomains, i.e. there's fed.wiki.org , and then there's ward.fed.wiki.org.

Is it an easy modification to enable the multiple subdomains?  Is there a differentiation here between the subdomain, and a wiki farm?  I presume a wiki farm would allow more users to sign up, which isn't my direction.  I would encourage people to follow a set of directions to set up their own federated wikis (or would help them to do so) so that separate identities are easily apparent.

**Comment by almereyda** [comment]
A wikifarm is exactly what you presume : One process which serves multiple subdomains. Actually, it will serve any `Host` Header it receives and create a seperate wiki for it. So make sure to limit access by a reverse proxy to selected domains.

See

* http://wiki.allmende.io (persistent) or
* http://federated.wiki (currently no guarantee of persistence)

which bot serve farms for all their respective subdomains (despite http://socio.federated.wiki - but that's another story).

**Comment by coevolving** [comment]
@almereyda Thanks for the pointer to http://wiki.allmende.io .  I see that when I try http://david.wiki.allmende.io , a new Welcome Visitors page comes up.

However, when I try http://david.fed.coevolving.com , I get "This web page is not available 
ERR_NAME_RESOLUTION_FAILED" .  This is an installation of the node.js version of Openshift.

Can I modify this installation into a wiki farm on Openshift?

**Comment by paul90** [comment]
There are three steps in converting from a single site to a farm.

1. The files for the sites within a farm are stored in directories with the name of the domain, under the `.wiki` directory, rather than directly within that directory. At the simplest this will involve creating a directory for the farm site(s) under in `.wiki` and copying the `pages` and `status` directories there. So, using your current site as an example you would create `.wiki/fed.coevolving.com`.

2. DNS and the hosting service needs to be configured to accept the names you want to use within the farm. This is done the same way you would have setup /fed.coevolving.com. While you can point a DNS wildcard to OpenShift, each site in the farm will need to be individually added to OpenShift using the application console.

3. Change the wiki startup to use farm mode - this needs a couple of lines being uncommented in `server.js` in the OpenShift quickstart.

**Comment by paul90** [comment]
@coevolving - I'm proposing to make Farm Mode the default in the next version of the OpenShift quickstart. Would this cause you a problem?

**Comment by coevolving** [comment]
@paul90 Thanks for asking.  Actually, I would really welcome the Farm Mode as the default, and I think that it will reduce a speed bump for newbies from when they get started to when they are actively populating a federated wiki.  

I'm looking forward to the improved function.  

The only question is whether this will impact the CNAME from using my own domain on login, masking the rhcloud.  I had written up my configuration work at http://fed.coevolving.com/view/welcome-visitors/view/wiki-openshift-quickstart .

**Comment by paul90** [comment]
Looking at that page, the need for step (f) is removed.

The DNS setup you have using a CNAME to point to site stays the same, but you will just need to move the sites `pages` and `status` directories into the farm site directory, into `$OPENSHIFT_DATA_DIR/fed.coevolving.com` in your case.

**Comment by paul90** [comment]
The OpenShift Quickstart has now been updated. As with any upgrade it is good to take a backup, just in case.

How to update is covered in the readme file over at [paul90/wiki-openshift-quickstart](https://github.com/paul90/wiki-openshift-quickstart). 

Those who have been running without farm mode will need to move the pages and status directories as detailed a few comments ago, and quoted below:

> The files for the sites within a farm are stored in directories with the name of the domain, under the OPENSHIFT_DATA_DIR directory, rather than directly within that directory. At the simplest this will involve creating a directory for the farm site(s) under in OPENSHIFT_DATA_DIR and copying the pages and status directories there. So, using your current site as an example you would create fed.coevolving.com in the OPENSHIFT_DATA_DIR directory, and move the pages and status directories there.

**Comment by opn** [comment]
@paul90 I'm interested in how you might create a wiki farm on a localhost served up on the LAN. While I could start the farm by passing a param on the command line - I was stumped by the lack of equivalent of a DNS wildcard over the LAN. Any thoughts on this would be much appreciated as using this in dynamic teaching situations with poor internet connectivity has come up a few times now?

**Comment by WardCunningham** [comment]
It might be possible with zeroconf networking. Some quick poking around surfaced this item that discusses the issue.

http://stackoverflow.com/questions/775233/how-to-route-all-subdomains-to-a-single-host-using-mdns

Presumably I could configure *.ward.local to be a farm served by my laptop and accessible to all on what ever LAN I was on at the moment.

**Comment by paul90** [comment]
Probably worth looking at [DNS Service Discovery](http://www.dns-sd.org/) and [Multicast DNS](http://www.multicastdns.org/). There is also a [script](https://gist.github.com/gdamjan/3168336) to register a mDNS/DNS-SD alias which might be of use.

With poor internet connectivity claiming, and signing in, to your wiki is likely to be problem.

**Comment by coevolving** [comment]
@opn Just following your questions, I'm wondering if this idea of disconnection is training issue or a feature request.  (What is the path of least astonishment?)  

My understanding of federated wiki enables anyone who isn't logged in can fork and edit pages, but they'll be saved in local storage rather than the remote storage when logged in.  If a person is working locally, then the pane is shaded a different colour, which could be overlooked by the novice.  Further, the idea of local versus remote may not be obvious to someone just typing into his or her browser, who might later complain that the new content hasn't been saved, and is "lost".  

@WardCunningham, my intuitive expectation of the way that local and remote should work is similar to the original Blackberry pitch:  I could read my e-mail until I got onto the plane, and could even respond to e-mail while on the plane, but the synchronization between local and remote wouldn't happen until I landed and got a server connection again.  My sense is that we're NOT playing that story with federated wiki.  Should we, or what is the story?

**Comment by WardCunningham** [comment]
@coevolving, you have the story right.

* When you are editing online in the airport each edit goes to the server and is "published" immediately.
* When you edit on the plane, the puts to the server fail, so changes are saved locally (see note).
* When you land, your edits stay local until you "fork" them back to the server.

The behavior is similar to running a local wiki on your laptop while in the air except that you don't have to start a server. Browser local storage is persistent through browser restarts so you can safely shut down your computer during landing.

Note: There is a persistent bug in this fail-over logic. The work around is to reload the tab when the fail happens. A similar failure happens when the server's login times out.

**Comment by coevolving** [comment]
@paul90 Thanks for your efforts on upgrading the Node version.  I still feel like a newbie with Git and Openshift, so I couldn't do this without your guidance.  

(1) Backing up the pages and status directories before upgrading was a good idea.  I could SSH onto Openshift, but couldn't get the SCP to work.  Finally, an alternative method of "Using FileZilla and SFTP on Windows with OpenShift" at https://blog.openshift.com/using-filezilla-and-sftp-on-windows-with-openshift/ enabled me to upload / download files.  

(2) After the Git push, the wiki site came up as new.  I noticed the pages and status directories under the data directory, and tried moving them (to the data/fed.coevolving.com directory) using a Filezilla drag-and-drop.  Somehow, the pages and status directories turned up empty, so I uploaded from the previously downloaded backup.  (Big relief!).  The web site looks much like it did before.

(3) I noticed that in addition to the data/fed.coevolving.com directory, there's a data/fed-coevolving.rhcloud.com directory.  When I surf to http://fed-coevolving.rhcloud.com/view/welcome-visitors, there's a big red page warning "Phishing attack ahead" from Google.  In theory, there shouldn't be anybody on that page anyway, so this may not be worth worrying about.

(4) On June 12, you had written:  
-- begin paste --
DNS and the hosting service needs to be configured to accept the names you want to use within the farm. This is done the same way you would have setup /fed.coevolving.com. While you can point a DNS wildcard to OpenShift, each site in the farm will need to be individually added to OpenShift using the application console.
-- end paste --
I'm not sure what behaviour is expected.  Does farm mode mean that I should eventually not only have fed.coevolving.com , but also alexandrian.fed.coevolving.com ... or would that be alexandrian.coevolving.com?  Would I create the additional data directories manually first, and then set up the DNS ... or the other way around?  

(5) The HTML markup that was previously working is now not working, e.g. http://fed.coevolving.com/view/welcome-visitors/view/digests-from-sfw-meetings/view/digest-2015-06-17 is rather ugly.  Did I forget to do something to make the HTML show up as desired?  

I'm glad to now not be downlevel!  Since it's been almost a year since I last added real content, I'll need to refactor the wiki content across the farm to make the neighbourhoods more tractable.

**Comment by paul90** [comment]
> (3) I noticed that in addition to the data/fed.coevolving.com directory, there's a data/fed-coevolving.rhcloud.com directory. When I surf to http://fed-coevolving.rhcloud.com/view/welcome-visitors, there's a big red page warning "Phishing attack ahead" from Google. In theory, there shouldn't be anybody on that page anyway, so this may not be worth worrying about.

But, going to http://fed-coevolving.rhcloud.com/ works, and redirects to the link above - but refreshing the page gets the red warning page. Google have a page for reporting false positives, https://www.google.com/safebrowsing/report_error/ , but as it's on the links that contain the line-up...

I get the same with wiki-paul90.rhcloud.com. I have reported the problem with both sites to google, but you don't have to look too far to see such false positives are legion.

> I'm not sure what behaviour is expected. Does farm mode mean that I should eventually not only have fed.coevolving.com , but also alexandrian.fed.coevolving.com ... or would that be alexandrian.coevolving.com?

You could have any or all of those, depending on which names you set-up in DNS and forward to your OpenShift app. But each name will need to be added to the OpenShift app's list of aliases.

> Would I create the additional data directories manually first, and then set up the DNS ... or the other way around?

You can do either - creating the directories first though allows you to create the identity file in the status sub-directory so the wiki is created pre-owned.

> 5) The HTML markup that was previously working is now not working, e.g. http://fed.coevolving.com/view/welcome-visitors/view/digests-from-sfw-meetings/view/digest-2015-06-17 is rather ugly. Did I forget to do something to make the HTML show up as desired?

Ah, that's because we made a change some months ago so paragraph items don't allow HTML content.

It you SHIFT and double click on those paragraphs they will get converted to use the HTML plugin, and all should be well.

**Comment by paul90** [comment]
Worth mentioning that Google's [safe browsering diagnostics](http://www.google.com/safebrowsing/diagnostic?site=fed-coevolving.rhcloud.com) doesn't report anything - but going to the root of the site does not create a problem - it is only with the URLs with the page line up.

**Comment by paul90** [comment]
@coevolving looks as if http://fed-coevolving.rhcloud.com/view/welcome-visitors is no longer getting the red phishing warning. The diagnostics link above now shows that google have visited the site, and not find anything suspicious.

**Comment by WardCunningham** [comment]
This conversation seems completed so I will close the issue.
