### ISSUE TITLE
Shutting down persona.org in November 2016

### ISSUE THREAD

**Issue by paul90** [fedwiki/wiki#72]
Mozilla have just announced that persona.org is going to be closed, below is a copy of the announcement.

---

Hi Everyone,

When the Mozilla Identity team transitioned Persona to community
ownership, we committed resources to operational and security support
throughout 2014 [1], and renewed that commitment for 2015 [2].  Due to
low, declining usage, we are reallocating the project’s dedicated,
ongoing resources and will shut down the persona.org services that we run.

Persona.org and related domains will be taken offline on November 30th,
2016.

If you run a website that relies on Persona, you will need to implement
an alternative login solution for your users.  We have assembled a wiki
page with additional information and guidelines for migration [3], but
here are the important things you need to know:

Between now and November 30th, 2016, Mozilla will continue to support
the Persona service at a maintenance level:
- Security issues will be resolved in a timely manner and the services
  will be kept online, but we do not expect to develop or deploy any
  new features.
- Support will continue to be available on the dev-identity mailing
  list [4] and in the #services-dev IRC channel [5].
- All websites that rely on persona.org will need to migrate to
  another means of authentication during this period.

Beginning on November 30th, 2016, the Persona service hosted by Mozilla
will be decommissioned:
- All services hosted on the persona.org domain will be shut down.
- Mozilla will retain control of the persona.org domain and will
  not transfer it to a third party.
- Since the privacy of user data is of utmost importance to Mozilla,
  we will destroy all user data stored on the persona.org servers,
  and will not transfer it to third parties.

We intentionally designed Persona to expose email addresses rather than
opaque identifiers, which should ease the transition to other systems
that provide verified email addresses.  You can find guidelines on
alternative login solutions on the wiki [3] and we will continue to
update them over the coming year.  We strongly encourage affected teams
to openly discuss and blog about their migrations on the dev-identity
mailing list  so that others can learn from their experience.

Thank you for your support and involvement with Persona. If you have any
questions, please post them to the dev-identity mailing list.

  Ryan

[1]
http://identity.mozilla.com/post/78873831485/transitioning-persona-to-community-ownership
[2] https://groups.google.com/forum/#!topic/mozilla.dev.identity/rPIm7GxOeNU
[3]
https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers
[4] https://lists.mozilla.org/listinfo/dev-identity
[5] http://irc.mozilla.org/#services-dev

**Comment by interstar** [comment]
Ouch!

**Comment by almereyda** [comment]
I suppose, due to @paul90's recent refactorings, this will help bring
forward a WebID-(TLS/RSA) implementation.

**Comment by almereyda** [comment]
Meanwhile we could give this issue a more colourful tag to raise the awareness of its existential shadow in our cerebral correlates.

**Comment by coevolving** [comment]
Are there instructions about what we should do, with the Persona shutdown at the end of this month?

On the Openshift installation at http://coevolving.com , I figured out how to rsync the data to my Ubuntu laptop.  https://www.npmjs.com/package/wiki , I executed
```
$ npm outdated --silent -g | grep '^Package\|^wiki'
$ npm install -g wiki
```
I was way down level, and the install must have worked, because I could now surf to http://fed.coevolving.com/system/export.json , and save as to my laptop.

It seems like the regular Persona interface still works.  

@WardCunningham @WardCunningham  What do I need to do, to update?

I'm travelling in Finland, and won't get back for a while.  Please advise what I should do, to update.  Thanks.

**Comment by WardCunningham** [comment]
You have several choices. If you would like your piggy back on the login you already have on Github, Twitter or Google, you can install this security plugin and configure it accordingly.

https://github.com/fedwiki/wiki-security-passportjs

If you are comfortable looking through your .wiki directory and finding status files then you might want to try the self-hosted identity provided here.

https://github.com/fedwiki/wiki-security-friends

For those of us with wiki farms and lots of users we offer an identity conversion process. You may have gotten email from me if you've claimed a site on one of my farms. The process has two steps, one for the farm operator and another for each site owner.

Farm operator migrates persona identity to a passport.js compatible version. Then configures one or more of the continuing identity providers as described above.
```
wiki-migrate
```
The farm site owner logs in with persona, clicks the people-plus icon next to the lock, and then logs in with the new identity provider. This completes the conversion for all of the sites that owner has on that farm.

It is also possible to do nothing. Then your site becomes read-only until you administer some other configuration. You should be able to unclaim a site by erasing the credentials in the site/status directory, restarting the server, discarding any session cookies and refreshing your browser window. Then claim your site by the new means you have configured.

We have created many paths forward for the many possible configurations of federated wiki. I have personally used most of them. We all have @paul90 to thank for the effort he put into both understanding the options and providing solutions for each one of them. This wasn't anything any one of us wanted to do but do it we must.

**Comment by coevolving** [comment]
If I were just installing federated wiki now, anew, which would be the default? wiki-security-passport or wiki-security-passport? Or is this an option upon installation?

I think that I can manage either update. I would prefer to be in line with the reference implementation. Thanks.

**Comment by coevolving** [comment]
Or does it make a difference whether the wiki is be configured as for an individual, or as a farm? I expect to have different installations of both in the near future. As a farm landlord, I would invite specific tenants rather than just have migrants randomly showing up.

**Comment by WardCunningham** [comment]
The software installs with many options. When you start the server you choose which options will be used. If you specify no security module then no one can write through the web interface. This would be useful if you were authoring on another system and publishing pages with file transfer.

**Comment by WardCunningham** [comment]
The security modules work the same with or without running a server as a farm. What matters is what the site owners would find convenient. You can configure all three of Github, Twitter and Google as identity providers and then let your potential site owners choose which source they trust. ( @paul90 check me on this )

An area of convenience for your site owners is what they do when they forget their password. Each of those services have password recovery processes. The Friends security module expects your friends to call you for help and you would provide them with a recovery code which you would find in the site/status/owner.json using your privileged access to the server through, say, ssh. Friends become owners upon first reference. The recovery code is made at that time. This supports the "let's make you a site together on your computer" workflow.

**Comment by coevolving** [comment]
@WardCunningham ok, I decided to go with Google as an indentity provider.  The instructions on getting the keys for the OAuth client on the Google website are straightforward.

How do I install wiki-security-passportjs on my Openshift installation?  I have SSH so that I can see the the app-root/data directory.  I tried to clone from git, but don't have the right credentials.  I must be thinking about this entirely the wrong way.

**Comment by paul90** [comment]
The OpenShift quick start was updated fairly recently, and includes the passport.js security module.

If you pull in the upstream changes to the repo for your OpenShift site (see https://github.com/paul90/wiki-openshift-quickstart#pulling-in-changes-to-wiki-openshift-quickstart), and redeploy will get the software updated.

Config should be handled the same way as wiki, so if you create a `config.json` in the `OPENSHIFT_DATA_DIR` it should be picked up.

**Comment by coevolving** [comment]
@paul90 I think I've done as you said, but am still getting the Persona login.

Firstly, I had to reinstall the rhc app and git on this laptop, as it's a different one from the one I had originally used. 

I added a config.json into the data directory.

`[fed-coevolving.rhcloud.com data]\> ls 

config.json  fed.coevolving.com		 node-v0.10.28-linux-x64
downloads    fed-coevolving.rhcloud.com  node-v0.10.39-linux-x64`

From my terminal, I then entered:

`daviding@di-x230t-3434cto:~/wiki$ git add .
daviding@di-x230t-3434cto:~/wiki$ git commit -m "put config.json in data directory"
[master 20dae68] put config.json in data directory
 1 file changed, 10 deletions(-)
daviding@di-x230t-3434cto:~/wiki$ git push
warning: push.default is unset; its implicit value has changed in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the traditional behavior, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

Since Git 2.0, Git defaults to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 302 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: 
remote:   - pre_stop_nodejs: Adding Node.js version 6.9.1 binaries to path
remote:   - PATH set to include custom node version (6.9.1) from
remote:        /var/lib/openshift/583f151789f5cf6940000023/app-root/data//node-v6.9.1-linux-x64/bin 
remote:     PATH = /var/lib/openshift/583f151789f5cf6940000023/app-root/data//node-v6.9.1-linux-x64/bin:/var/lib/openshift/583f151789f5cf6940000023/app-root/runtime/repo/node_modules/.bin:/var/lib/openshift/583f151789f5cf6940000023//.node_modules/.bin:/opt/rh/nodejs010/root/usr/bin:/bin:/usr/bin:/usr/sbin
remote: Stopping NodeJS cartridge
remote: Wed Nov 30 2016 13:57:25 GMT-0500 (EST): Stopping application 'wiki' ...
remote: Wed Nov 30 2016 13:57:26 GMT-0500 (EST): Stopped Node application 'wiki'
remote: Saving away previously installed Node modules
remote: Building git ref 'master', commit 20dae68
remote: 
remote:   - Checking to see if Node.js version 6.9.1 is installed ... 
remote:   - Node.js version 6.9.1 is already installed
remote: Building NodeJS cartridge
remote:   - PATH set to include custom node version (6.9.1) from
remote:        /var/lib/openshift/583f151789f5cf6940000023/app-root/data//node-v6.9.1-linux-x64/bin 
remote:     PATH = /var/lib/openshift/583f151789f5cf6940000023/app-root/data//node-v6.9.1-linux-x64/bin:/var/lib/openshift/583f151789f5cf6940000023/app-root/runtime/repo/node_modules/.bin:/var/lib/openshift/583f151789f5cf6940000023//.node_modules/.bin:/opt/rh/nodejs010/root/usr/bin:/bin:/usr/bin:/usr/sbin
remote:   - Installing dependencies w/ new version of npm ... 
remote: 
remote: npm info it worked if it ends with ok
remote: npm info using npm@3.10.8
remote: npm info using node@v6.9.1
remote: npm info lifecycle Wiki-on-OpenShift@0.5.0~preinstall: Wiki-on-OpenShift@0.5.0
remote: npm info linkStuff Wiki-on-OpenShift@0.5.0
remote: npm info lifecycle Wiki-on-OpenShift@0.5.0~install: Wiki-on-OpenShift@0.5.0
remote: npm info lifecycle Wiki-on-OpenShift@0.5.0~postinstall: Wiki-on-OpenShift@0.5.0
remote: npm info lifecycle Wiki-on-OpenShift@0.5.0~prepublish: Wiki-on-OpenShift@0.5.0
remote: npm info ok 
remote:   - Updating dependencies ... 
remote: 
remote: /var/lib/openshift/583f151789f5cf6940000023/app-root/runtime/repo/.openshift/action_hooks/build: line 37: export: `=': not a valid identifier
remote: /var/lib/openshift/583f151789f5cf6940000023/app-root/runtime/repo/.openshift/action_hooks/build: line 37: export: `/tmp': not a valid identifier
remote: Preparing build for deployment
remote: Deployment id is 310a2ae7
remote: Activating deployment
remote:   - Checking to see if Node.js version 6.9.1 is installed ... 
remote:   - Node.js version 6.9.1 is already installed
remote: 
remote:   - pre_start_nodejs: Adding Node.js version 6.9.1 binaries to path
remote:   - PATH set to include custom node version (6.9.1) from
remote:        /var/lib/openshift/583f151789f5cf6940000023/app-root/data//node-v6.9.1-linux-x64/bin 
remote:     PATH = /var/lib/openshift/583f151789f5cf6940000023/app-root/data//node-v6.9.1-linux-x64/bin:/var/lib/openshift/583f151789f5cf6940000023/app-root/runtime/repo/node_modules/.bin:/var/lib/openshift/583f151789f5cf6940000023//.node_modules/.bin:/opt/rh/nodejs010/root/usr/bin:/bin:/usr/bin:/usr/sbin
remote: Starting NodeJS cartridge
remote: Wed Nov 30 2016 13:58:53 GMT-0500 (EST): Starting application 'wiki' ...
remote: Waiting for application port (8080) become available ...
remote: Found 127.5.98.129:8080 listening port
remote: -------------------------
remote: Git Post-Receive Result: success
remote: Activation status: success
remote: Deployment completed with status: success
To ssh://583f151789f5cf6940000023@wiki-coevolving.rhcloud.com/~/git/wiki.git/
   4d51f1b..20dae68  master -> master
daviding@di-x230t-3434cto:~/wiki$ ls
CHANGES.md  deplist.txt  index.html  node_modules  package.json  server.js
cli.coffee  farm.coffee  LICENSE     OPENSHIFT.md  README.md
`

So, what am I doing wrong?

**Comment by paul90** [comment]
There is a migrate script that needs running `wiki-migrate`, which will need the location of the wiki data files passing. So run `wiki-migrate -d $OPENSHIFT_DATA_DIR`  this will create a `owner.json` for each of the wiki sites in the farm.

I don't see a login on `http://fed-coevolving.rhcloud.com/`, so it looks as if the configuration file is not getting picked up, and the site is falling back to read only mode. In the message above, it looks as if you've created it in git, which is the wrong place, `$OPENSHIFT_DATA_DIR` is the directory that contains wiki site data (and does not get overwritten when the application is updated).

**Comment by coevolving** [comment]
@paul90 Sorry that I'm a real newbie on this, because I don't use git much, just ssh.

Is wiki-migrate run locally an my laptop where rhc app is installed?

When you say $OPENSHIFT_DATA_DIR , my presumption has been that you don't mean that literally.  When I ssh in, the directory structure is ...
`app-deployments  app-root  git	nodejs`

.. and then I enter app-root to find ...
`build-dependencies  data  dependencies	logs  repo  runtime`

My assumption is that git only impacts the programs, and not the data, so I really don't understand what's going on.

**Comment by paul90** [comment]
You need to run wiki-migrate on the server.

`$OPENSHIFT_DATA_DIR` should be pointing to app-root/data

**Comment by coevolving** [comment]
@paul90 Where is wiki-migrate?

`[fed-coevolving.rhcloud.com 538f7aeb5973ca83160008a6]\> ls 

app-deployments  app-root  git	nodejs 

[fed-coevolving.rhcloud.com 538f7aeb5973ca83160008a6]\> wiki-migrate -d app-root/data 

bash: wiki-migrate: command not found`

**Comment by paul90** [comment]
Looks as if that didn't get copied over wiki package...

I have added it to the quickstart repo.

I notice that Mozilla have not managed to complete moving at least one of their sites...
